### ISSUE TITLE
Incorrect use of '=' operator

### ISSUE THREAD

**Issue by IlyesAbdelhamid** [manhowong/matlab-venn#1]
Hello, 

In running the command venn(3), I got the following errors:
**Error: File: venn.m Line: 109 Column: 26
Incorrect use of '=' operator. To assign a value to a variable, use '='. To compare values for equality, use '=='.**

I am using MATLAB R2019a

Could you help me with this matter?
Thank you in advance for your help.

Sincerely,
Ilyes

**Comment by manhowong** [comment]
Hi Ilyes, thank you for reaching out!
This error was caused by the unsupported name-value syntax for the input arguments before R2021a. If you are interested, you can find more info here:
[https://www.mathworks.com/matlabcentral/discussions/highlights/134409-new-in-r2021a-name-value-syntax](https://www.mathworks.com/matlabcentral/discussions/highlights/134409-new-in-r2021a-name-value-syntax)

I have changed the name-value syntax in `venn.m`, so it should support R2019a now. Just one more thing: For R2019a, please also use the comma-separated syntax when calling the function `venn`. (See the link above)

I have uploaded the new version to this repo. Please replace the old `venn.m` with it and try again with comma-separated syntax. For example, write:
```
venn(3,'sets',{'A' 'B' 'C'});
```
instead of:
```
venn(3,sets={'A' 'B' 'C'});
```

Thanks again for reporting the bug! Please let me know if it works for you.

Cheers,
Man Ho

**Comment by IlyesAbdelhamid** [comment]
Hello,

I confirm that the code works.
Thank you!

Sincerely,
Ilyes

**Comment by manhowong** [comment]
I am glad it works. Thank you for your feedback :)
Man Ho
